# THEME SETTINGS
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # Options: "air", "contrast", "dark", "sunrise"
locale: "en-US"
title: "Vadim Atlassov"
description: "Researcher in Generative Models & Medical AI"
url: "https://vadim-atl.github.io" # <--- CHANGE THIS TO YOUR URL

# AUTHOR SIDEBAR (The left side of Minsun's site)
author:
  name: "Vadim Atlassov"
  avatar: "/assets/images/profile.png" # We will add this image in Step 4
  bio: "Researcher at **Nazarbayev University**.<br>Generative Models & Medical AI."
  location: "Astana, Kazakhstan"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:vadim.atlassov@nu.edu.kz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vadim-ATL"
    - label: "Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "CV / Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "https://github.com/Vadim-ATL/Vadim-ATL/blob/main/CV.pdf"

# PLUGINS
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache