title: "Vadim Atlassov - PhD Portfolio"
description: "Researcher in Generative Models & Medical AI | Controllable Diffusion Models for Medical Imaging"
baseurl: ""
url: "https://Vadim-ATL.github.io"
theme: jekyll-theme-minimal

author:
  name: "Vadim Atlassov"
  email: "vadim.atlassov@nu.edu.kz"
  github: "Vadim-ATL"
  scholar: "https://scholar.google.com/citations?user=ipi5AVsAAAAJ"

header_pages:
  - index.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  publications:
    output: true
  projects:
    output: true

markdown: kramdown
kramdown:
  input: GFM
