remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
locale: "en-US"
title: "Vadim Atlassov"
description: "Researcher in Generative Models & Medical AI"
url: "https://vadim-atl.github.io" 

author:
  name: "Vadim Atlassov"
  avatar: "/assets/images/profile.jpg"
  bio: "Researcher at **Nazarbayev University**.<br>Generative Models & Medical AI."
  location: "Astana, Kazakhstan"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:vadim.atlassov@nu.edu.kz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vadim-ATL"
    - label: "Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=ipi5AVsAAAAJ"
    - label: "CV (PDF)"
      icon: "fas fa-fw fa-file-pdf"
      url: "https://github.com/Vadim-ATL/CV.pdf"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true